version: "3.8"

networks:
  appnet:

volumes:
  api_node_modules:
  database:

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: ./api
        target: /usr/api
      - type: volume
        source: api_node_modules
        target: /usr/api/node_modules
    networks:
      - appnet
    ports:
      - 8000:8000
    depends_on:
      - db

  db:
    image: mongo:4.4-bionic
    networks:
      - appnet
    ports:
      - 27017:27017
    volumes:
      - type: volume
        source: database
        target: /data/db
